feat: added initialPage optional Parameter
nilsmehlhorn/ngx-pagination-data-source pull request #24
Opened 2021-10-08 09:04 UTC by alexfarrugia

hi @nilsmehlhorn, i created a PR for this minor feature as discussed in the thread. I also tested it on my existing application. It seems to work ok both in a scenario where you don't need to initialise the page number as well as when you do. Let me know your thoughts. Thanks

2021-10-10 12:50 UTC, nilsmehlhorn requested changes
Thanks for your work! Would you mind adding a test case inside `pagination-data-source.spec.ts` for this feature?

2021-10-10 12:50 UTC, nilsmehlhorn commented on projects/ngx-pagination-data-source/src/lib/pagination-data-source.ts
> +    private firstCall = true,
Is it necessary to have this as a class property or even a constructor parameter? Wouldn't it suffice to have it as a local variable inside the constructor?

2021-10-14 08:14 UTC, nilsmehlhorn approved these changes

2021-10-14 08:18 UTC, merged

2021-10-14 08:36 UTC, alexfarrugia commented on projects/ngx-pagination-data-source/src/lib/pagination-data-source.ts
> +    private firstCall = true,
thanks @nilsmehlhorn , just realised that i didn't update the readme.md - shall i write something about this change?